### ISSUE TITLE
product-details-page

### ISSUE THREAD

**Issue by timashoff** [timashoff/online-store#4]
## страница с описанием товаров / product detail page

description task [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store-team/modules/product-details-page.md)

in-stock:
![Image](https://user-images.githubusercontent.com/83927854/210774266-9644f90b-df5d-4742-b2c0-df963aa0c116.png)
out-of-stock
![Image](https://user-images.githubusercontent.com/83927854/210775852-64b8950b-77b6-44f3-9984-f980c9a927fa.png)

```css
/* CSS Common Styles */
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap');

:root {
  --grey-color: #999;
  --orange-color: #f60;
  --orange-color-hover: rgba(255, 102, 0, 0.8);
  --main-info-color: #333;
  --main-info-color-hover: rgba(51, 51, 51, 0.9);

  --main-info-font-size: 18px;
  /* 1.125 rem */
  --path-font-size: 14px;
  /* 0.875 rem */
  --title-font-size: 24px;
  /* 1.5 rem */
}

* {
  box-sizing: border-box;
}

body {
  font-family: 'JetBrains Mono', monospace;
  font-size: 1rem;
}
```
